- name: install epel
  yum: name=epel-release state=latest

- name: install git
  yum: name=git state=latest

- name: install vim
  yum: name=vim state=latest

- name: install prerequisites for ansible module
  yum: name=libselinux-python state=latest

- name: install prerequisites for ruby
  yum: name={{ item }} state=latest
  with_items: "{{prerequisites}}"

- name: install http-parser
  yum: name=https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm

- name: install qt5
  yum: name=qt5-qtwebkit-devel