site:
  name: "Property Suneikii"
  region: 'th'
  provider: "Suneikii.com"
  page_description: "SuneikiiはRuby on Railsで作られたブログアプリケーションです"
  meta:
    og:
      locale: 'en_US'
      type:   'website'
      image:  'sample.jpg'
    twitter:
      card:   'summary_large_image'
      site:   '@XXXX'