provider:
  facebook:
    api_key: 'dev_api'
    secret_key: ''

  twitter:
    api_key: 'dev_api'
    secret_key: ''

  instagram:
    api_key: '5ea2ce402cd549c19c280bef8df56565'
    secret_key: '4be82c89388d44f39a7f6a3448844c6e'

  github:
    api_key:    'b867001e68d1c14d9809'
    secret_key: '07e1ab4ad22dfba1b50dd3a74a9385c5705406d8'
    scope:      'user:email'

  flickr:
    api_key: 'dev_api'
    secret_key: ''

  foursquare:
    api_key: 'dev_api'
    secret_key: ''