provider:
  facebook:
    api_key: 'dev_api'
    secret_key: ''

  twitter:
    api_key: 'dev_api'
    secret_key: ''

  instagram:
    api_key: '9bdcc2ae1e27485dbbffa9559f074596'
    secret_key: 'fa9e704262254b6a8450a2145540e064'

  github:
    api_key:    '883a8c8eb0abdc724eeb'
    secret_key: '4a544f604193f4e45b2bd5113e0fd076c4f8177b'
    scope:      'user:email'

  flickr:
    api_key: 'dev_api'
    secret_key: ''

  foursquare:
    api_key: 'dev_api'
    secret_key: ''