---
- hosts: all
  become: true
  user: vagrant

  roles:
   - { role: initial_install        }
   - { role: init                   }
   - { role: figlet                 }
   - { role: rbenv                  }
   - { role: ruby_install           }
   - { role: rails_install          }
   - { role: mysql                  }
#   - { role: bundle                 }
   - { role: zsh                    }
   - { role: redis                  }
#   - { role: npm                    } # TODO :: R.I.P. PhantomJS